apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: thrive-mind-client
spec:
  selector:
    matchLabels:
      app: thrive-mind-client
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: thrive-mind-client
    spec:
      containers:
        - name: thrive-mind-client
          image: ddkpham/thrive-mind-client:v2
          ports:
            - containerPort: 80
